onlyBuiltDependencies:
  - esbuild
  - msw
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - react@19.2.1
  - react-dom@19.2.1
  - eslint-config-next@15.5.7
  - next@15.5.7
  - "@next/eslint-plugin-next@15.5.7"
  - "@next/env@15.5.7"
  - "@next/swc-linux-x64-gnu@15.5.7"
  - "@next/swc-linux-x64-musl@15.5.7"
  - "@next/swc-darwin-arm64@15.5.7"
  - "@next/swc-darwin-x64@15.5.7"
  - "@next/swc-win32-x64-msvc@15.5.7"
  - "@next/swc-win32-arm64-msvc@15.5.7"
  - "@next/swc-linux-arm64-gnu@15.5.7"
  - "@next/swc-linux-arm64-musl@15.5.7"
