/** Screens that participate in linear programs. */
export enum ScreenId {
  Intro = 'intro',
  RevenueIntro = 'revenue-intro',
  WarehouseIntro = 'warehouse-intro',
  SourceMapsIntro = 'source-maps-intro',
  SourceMapsDetect = 'source-maps-detect',
  SourceMapsOutro = 'source-maps-outro',
  MigrationIntro = 'migration-intro',
  AgentSkillIntro = 'agent-skill-intro',
  AiObservabilityIntro = 'ai-observability-intro',
  MetricsIntro = 'metrics-intro',
  ErrorTrackingIntro = 'error-tracking-intro',
  ErrorTrackingDetect = 'error-tracking-detect',
  SelfDrivingIntro = 'self-driving-intro',
  SelfDrivingIntegrationCheck = 'self-driving-integration-check',
  SelfDrivingIntegrationDetect = 'self-driving-integration-detect',
  SelfDrivingHandoff = 'self-driving-handoff',
  SelfDrivingGithub = 'self-driving-github',
  AuditIntro = 'audit-intro',
  AuditRun = 'audit-run',
  AuditOutro = 'audit-outro',
  HealthCheck = 'health-check',
  DoctorIntro = 'doctor-intro',
  DoctorReport = 'doctor-report',
  Setup = 'setup',
  Auth = 'auth',
  Run = 'run',
  Mcp = 'mcp',
  McpSuggestedPrompts = 'mcp-suggested-prompts',
  SlackConnect = 'slack-connect',
  KeepSkills = 'keep-skills',
  Outro = 'outro',
  MintFailure = 'mint-failure',
  Exit = 'exit',
  McpAdd = 'mcp-add',
  McpRemove = 'mcp-remove',
  AiOptIn = 'ai-opt-in',
}

/** Screens that interrupt programs as overlays */
export enum Overlay {
  SettingsOverride = 'settings-override',
  ManagedSettings = 'managed-settings',
  PortConflict = 'port-conflict',
  ManualAuthCode = 'manual-auth-code',
  AuthError = 'auth-error',
  SessionTimeout = 'session-timeout',
  WizardAsk = 'wizard-ask',
  TaskNotice = 'task-notice',
}
