import fs from 'fs';
import path from 'path';
import { logToFile } from './debug';

const MARKER_FILENAME = '.posthog-wizard.json';

export type WizardMarker = {
  _comment: string;
  status: 'success' | 'error';
  integration: string;
  completedAt: string;
  wizardVersion: string;
};

export type RerunReason =
  | 'fresh_install'
  | 'retry_after_error'
  | 'rerun_after_success'
  | 'manual_install';

/**
 * Read an existing wizard marker from the project directory.
 * Returns null if no marker exists or it can't be parsed.
 */
export async function readWizardMarker(
  installDir: string,
): Promise<WizardMarker | null> {
  const markerPath = path.join(installDir, MARKER_FILENAME);
  try {
    const content = await fs.promises.readFile(markerPath, 'utf-8');
    return JSON.parse(content) as WizardMarker;
  } catch {
    return null;
  }
}

/**
 * Write a wizard marker to the project directory.
 * This records whether the wizard succeeded or failed so future
 * runs can classify the reason for re-running.
 */
export async function writeWizardMarker(
  installDir: string,
  data: Pick<WizardMarker, 'status' | 'integration'>,
): Promise<void> {
  const markerPath = path.join(installDir, MARKER_FILENAME);

  let wizardVersion = 'unknown';
  try {
    const pkg = JSON.parse(
      await fs.promises.readFile(
        path.join(__dirname, '../../package.json'),
        'utf-8',
      ),
    );
    wizardVersion = pkg.version ?? 'unknown';
  } catch {
    // Non-critical — proceed with 'unknown'
  }

  const marker: WizardMarker = {
    _comment:
      'Auto-generated by the PostHog setup wizard. Safe to delete. https://posthog.com/docs/wizard',
    status: data.status,
    integration: data.integration,
    completedAt: new Date().toISOString(),
    wizardVersion,
  };

  try {
    await fs.promises.writeFile(
      markerPath,
      JSON.stringify(marker, null, 2) + '\n',
      'utf-8',
    );
  } catch (error) {
    // Non-critical — don't break the wizard if we can't write the marker
    logToFile(`[Marker] Failed to write ${markerPath}: ${error}`);
  }
}

/**
 * Classify why the user is re-running the wizard based on
 * the marker file and whether PostHog is already installed.
 */
export function classifyRerunReason(
  marker: WizardMarker | null,
  posthogAlreadyInstalled: boolean,
): RerunReason {
  if (marker) {
    return marker.status === 'success'
      ? 'rerun_after_success'
      : 'retry_after_error';
  }

  return posthogAlreadyInstalled ? 'manual_install' : 'fresh_install';
}
