import type { WizardStore } from './store.js';

/**
 * Every WizardStore member the tui, the cli, and the e2e harness may touch.
 * The architecture suite derives the real usage and fails when the two drift,
 * so widening the boundary is an explicit edit here.
 */
export const STORE_BOUNDARY_MEMBERS = [
  'activeProgram',
  'addDiscoveredFeature',
  'analyticsProgramId',
  'backupAndFixSettingsOverride',
  'cancelPendingQuestion',
  'chooseProvisionAccount',
  'completeRunStep',
  'completeSetup',
  'confirmSelfDrivingHandoff',
  'currentScreen',
  'currentStage',
  'declineGithub',
  'declineSharing',
  'dismissManualAuthCode',
  'dismissOutage',
  'enableFeature',
  'eventPlan',
  'getGate',
  'getSnapshot',
  'grantSharing',
  'hasInterrupt',
  'interruptDepth',
  'pushStatus',
  'resolvePendingQuestion',
  'resolvePortConflict',
  'resolveTaskNotice',
  'runInitHooks',
  'runReadyHooks',
  'session',
  'setApiUser',
  'setCredentials',
  'setCurrentStage',
  'setDetectedFramework',
  'setEventPlan',
  'setFrameworkConfig',
  'setFrameworkContext',
  'setGithubConnected',
  'setHandoffText',
  'setIntegrate',
  'setLoginUrl',
  'setMcpComplete',
  'setMcpSuggestedPromptsDismissed',
  'setMintHandoff',
  'setOutroData',
  'setOutroDismissed',
  'setReadinessResult',
  'setRoleAtOrganization',
  'setRunPhase',
  'setSkillsComplete',
  'setSlackConnected',
  'setSlackStepDismissed',
  'setSpellbook',
  'setTasks',
  'showManualAuthCode',
  'statusMessages',
  'submitManualAuthCode',
  'subscribe',
  'switchProgram',
  'syncTodos',
  'tasks',
  'tokenUsage',
  'version',
  'waitUntil',
] as const;

export type StoreBoundaryMember = (typeof STORE_BOUNDARY_MEMBERS)[number];

/** The store as other surfaces see it. */
export type WizardStoreApi = Pick<WizardStore, StoreBoundaryMember>;
